global:
    scrape_interval: 5s
    scrape_timeout: 3s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "api-gateway"
      metrics_path: /metrics
      static_configs:
          - targets: ["api-gateway:3333"]

    - job_name: "node-exporter"
      static_configs:
          - targets: ["node_exporter:9100"]

    - job_name: "pushgateway"
      honor_labels: true
      static_configs:
          - targets: ["pushgateway:9091"]
