name: CI/CD pipleline
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build_nodejs:
    name: Build and Test node.js service
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - path: ./api-gateway
          - path: ./microservices/auth-service
          - path: ./microservices/channel-service
          - path: ./microservices/notif-service
          - path: ./microservices/video-service
        node-version: [24.x]
        
    steps:
    - name: Copy repository
      uses: actions/checkout@v6
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.service.path }}/package-lock.json

    - name: Install dependencies for ${{ matrix.service.path }}
      working-directory: ${{ matrix.service.path }}
      run: npm ci

    - name: Run Linting
      working-directory: ${{ matrix.service.path }}
      run: npm run lint --if-present
      continue-on-error: true
      
    - name: Build ${{ matrix.service.path }}
      working-directory: ${{ matrix.service.path }}
      run: npm run build --if-present
      
    - name: Run tests for ${{ matrix.service.path }}
      working-directory: ${{ matrix.service.path }}
      run: npm test --if-present


  build_docker:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    needs: build_nodejs
    if: github.event_name != 'pull_request'

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: api-gateway
            dockerfile: ./api-gateway/Dockerfile
            context: ./api-gateway
          - service: auth-service
            dockerfile: ./microservices/auth-service/Dockerfile
            context: ./microservices/auth-service
          - service: channel-service
            dockerfile: ./microservices/channel-service/Dockerfile
            context: ./microservices/channel-service
          - service: notif-service
            dockerfile: ./microservices/notif-service/Dockerfile
            context: ./microservices/notif-service
          - service: video-service
            dockerfile: ./microservices/video-service/Dockerfile
            context: ./microservices/video-service

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with: 
          # registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request '}}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Generate artefact attestation
        if: success() && github.event.name != 'pull_request'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true 